server.port=8080

spring.datasource.url=jdbc:mysql://roundhouse.proxy.rlwy.net:21136/railway?useSSL=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=XzYqtKuXNcxTGVUoWcnLMZJkOnjbbYWZ
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
jwt.secret=MySuperSecretKeyForStudyPlannerApp2024XYZ
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=hannahjasmine273@gmail.com
spring.mail.password=aoouplqsjqbomrbp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true